name: Compilacao do texto 
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build_latex:
    runs-on: windows-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
      - name: Ação LaTeX
        uses: fudan-mse/latex-action@v0.0.1
            
        with:
          root_file: |
              main.tex
              text/ref.bib
              text/write.tex
